plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
    // id 'com.diffplug.spotless' version "7.0.0.BETA3" // Disabled for 1.21.8 port
}

neoForge {
    neoFormVersion = "1.21-20240613.152323"
    accessTransformers = ["../common/src/main/resources/META-INF/accesstransformer.cfg"]

    parchment {
        minecraftVersion = "${parchment_minecraft}"
        mappingsVersion = "${parchment_version}"
    }

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.7'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.4.1'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.4.1'
    // compileOnly "maven.modrinth:shoulder-surfing-reloaded:1.21.8-4.15.0+neoforge" # Version not available yet
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
